FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    libcurl4-openssl-dev \
    cmake \
    gcc \
    make \
    python3-pip \
    curl \
    libssl-dev \
    pkg-config \
    clang \
    git \
    neovim

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install nu
RUN cargo install bat

WORKDIR /usr/src/dev

CMD ["nu"]
